import React from "react";
import ReactDOM from "react-dom";
import { BrowserRouter as Router } from "react-router-dom";
import "./index.css";
import App from "./App";
import * as serviceWorker from "./serviceWorker";

// Import Auth0 SDK
import Auth0 from "@auth0/auth0-spa-js";
import { Route } from "react-router";
import Callback from "./Callback";

// Read config from environment variables generated by the CLI
const auth0Config = {
  domain: process.env.REACT_APP_AUTH0_DOMAIN,
  client_id: process.env.REACT_APP_AUTH0_CLIENT_ID,
  audience: process.env.REACT_APP_AUTH0_AUDIENCE,
  redirect_uri: process.env.REACT_APP_AUTH0_REDIRECT_URI
};

// Instantiate the SDK
const auth0 = new Auth0(auth0Config);

// Leverage audience identifier being the API URL to have only one setting for both
const apiBaseURL = auth0Config.audience;

const appProps = {
  // Pass Auth0 SDK instance as prop
  auth0,
  auth0Config,
  apiBaseURL
};

ReactDOM.render(
  <Router>
    <Route exact path="/callback" render={() => <Callback auth0={auth0} />} />
    <Route exact path="/" render={() => <App {...appProps} />} />
  </Router>,
  document.getElementById("root")
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
