import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
import * as serviceWorker from "./serviceWorker";

// Read config from environment variables generated by the CLI
const auth0Config = {
  domain: process.env.REACT_APP_AUTH0_DOMAIN,
  client_id: process.env.REACT_APP_AUTH0_CLIENT_ID,
  audience: process.env.REACT_APP_AUTH0_AUDIENCE,
  redirect_uri: process.env.REACT_APP_AUTH0_REDIRECT_URI
};

// Leverage audience identifier being the API URL to have only one setting for both
const apiBaseURL = auth0Config.audience;

ReactDOM.render(
  <App auth0Config={auth0Config} apiBaseURL={apiBaseURL} />,
  document.getElementById("root")
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
