import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

// Import Auth0 SDK
import Auth0 from "@auth0/auth0-login";

// Import API calling functions
import { createAPICaller, createAuthedAPICaller } from './api-access';

// Read config from environment variables generated by the CLI
const auth0Config = {
  domain: process.env.REACT_APP_AUTH0_DOMAIN,
  client_id: process.env.REACT_APP_AUTH0_CLIENT_ID,
  audience: process.env.REACT_APP_AUTH0_AUDIENCE
};

// Instantiate the SDK
const auth0 = new Auth0(auth0Config);

// Leverage audience identifier being the API URL to have only one setting for both
const apiBaseURL = auth0Config.audience;

// Create API calling functions
const callAPIWithToken = createAuthedAPICaller(auth0, apiBaseURL);
const callAPIWithoutToken = createAPICaller(apiBaseURL);

const appProps = {
  // Pass Auth0 SDK instance as prop
  auth0,

  // API calling functions
  callAPIWithToken,
  callAPIWithoutToken
};

ReactDOM.render(<App {...appProps} />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
